version: '3.8'

services:

  frontend:
    image: ghcr.io/plone/demo-frontend:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://demo-plone-org_backend:8080/Plone
    depends_on:
      - backend
    networks:
      - public
      - demoplone
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.demo-frontend.loadbalancer.server.port=3000
        # Router
        - traefik.http.routers.demo-frontend.rule=Host(`demo.plone.org`,`6.demo.plone.org`)
        - traefik.http.routers.demo-frontend.entrypoints=https
        - traefik.http.routers.demo-frontend.tls=true
        - traefik.http.routers.demo-frontend.tls.certresolver=le
        - traefik.http.routers.demo-frontend.service=demo-frontend
        - traefik.http.routers.demo-frontend.middlewares=gzip

  backend:
    image: ghcr.io/plone/demo-backend:latest
    networks:
      - public
      - demoplone
    deploy:
      # Just one, as we do not have a shared database
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.demo-backend.loadbalancer.server.port=8080
        # Middleware
        - "traefik.http.middlewares.demo-backend-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.demo-backend-vhm.replacepathregex.replacement=/VirtualHostBase/https/demo.plone.org/Plone/++api++/VirtualHostRoot/$$1"
        # Router
        - traefik.http.routers.demo-backend.rule=Host(`demo.plone.org`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.demo-backend.entrypoints=https
        - traefik.http.routers.demo-backend.tls=true
        - traefik.http.routers.demo-backend.service=demo-backend
        - traefik.http.routers.demo-backend.middlewares=gzip,demo-backend-vhm

  classic:
    image: ghcr.io/plone/demo-classic:latest
    networks:
      - public
    deploy:
      # Just one, as we do not have a shared database
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.demo-classic.loadbalancer.server.port=8080
        # Middleware
        - "traefik.http.middlewares.demo-classic-vhm.replacepathregex.regex=^/(.*)"
        - "traefik.http.middlewares.demo-classic-vhm.replacepathregex.replacement=/VirtualHostBase/https/classic.demo.plone.org/Plone/VirtualHostRoot/$$1"
        # Router
        - traefik.http.routers.demo-classic.rule=Host(`classic.demo.plone.org`)
        - traefik.http.routers.demo-classic.entrypoints=https
        - traefik.http.routers.demo-classic.tls=true
        - traefik.http.routers.demo-classic.service=demo-classic
        - traefik.http.routers.demo-classic.middlewares=gzip,demo-classic-vhm

  backend_volto:
    image: ghcr.io/plone/demo-backend-volto:latest
    networks:
      - public
      - demoplonevolto
    deploy:
      # Just one, as we do not have a shared database
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.demo-volto-backend.loadbalancer.server.port=8080
        # Middleware
        - "traefik.http.middlewares.demo-volto-backend-vhm.replacepathregex.regex=^/\\+\\+api\\+\\+($$|/.*)"
        - "traefik.http.middlewares.demo-volto-backend-vhm.replacepathregex.replacement=/VirtualHostBase/https/volto.demo.plone.org/Plone/++api++/VirtualHostRoot/$$1"
        # Router
        - traefik.http.routers.demo-volto-backend.rule=Host(`volto.demo.plone.org`) && (PathPrefix(`/++api++`))
        - traefik.http.routers.demo-volto-backend.entrypoints=https
        - traefik.http.routers.demo-volto-backend.tls=true
        - traefik.http.routers.demo-volto-backend.service=demo-volto-backend
        - traefik.http.routers.demo-volto-backend.middlewares=gzip,demo-volto-backend-vhm

  frontend_volto:
    image: ghcr.io/plone/demo-frontend-volto:latest
    environment:
      RAZZLE_INTERNAL_API_PATH: http://demo-plone-org_backend_volto:8080/Plone
    depends_on:
      - backend
    networks:
      - public
      - demoplonevolto
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.type == app
      labels:
        - traefik.enable=true
        - traefik.docker.network=public
        - traefik.constraint-label=public
        # Service
        - traefik.http.services.demo-frontend-volto.loadbalancer.server.port=3000
        # Router
        - traefik.http.routers.demo-frontend-volto.rule=Host(`volto.demo.plone.org`)
        - traefik.http.routers.demo-frontend-volto.entrypoints=https
        - traefik.http.routers.demo-frontend-volto.tls=true
        - traefik.http.routers.demo-frontend-volto.tls.certresolver=le
        - traefik.http.routers.demo-frontend-volto.service=demo-frontend-volto
        - traefik.http.routers.demo-frontend-volto.middlewares=gzip

networks:
  public:
    external: true
  demoplone:
    driver: overlay
  demoplonevolto:
    driver: overlay
