name: Deploy demo.plone.org

on:
  workflow_dispatch:
  
jobs:

  deploy:

    runs-on: ubuntu-latest
    environment: demo.plone.org
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to demo.plone.org
        uses: kitconcept/docker-stack-deploy@v1.2.0
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_GHCR_READ_TOKEN }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_private_key: ${{ secrets.DEPLOY_SSH }}
          stack_file: "devops/stacks/demo.plone.org.yml"
          stack_name: "demo-plone-org"
          deploy_timeout: 480
